default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: EasyPOS_development

test:
  <<: *default
  database: EasyPOS_test

production:
  <<: *default
  database: EasyPOS_production
  username: EasyPOS
  password: <%= ENV['CROSSOVERPOS_DATABASE_PASSWORD'] %>