default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: EasyPOS_development

test:
  <<: *default
  database: EasyPOS_test

production:
  <<: *default
  database: EasyPOS_production
  username: EasyPOS
  password: <%= ENV['EASYPOS_DATABASE_PASSWORD'] %>